### ISSUE TITLE
Make compatible with HHVM

### ISSUE THREAD

**Issue by LukasReschke** [punic/punic#41]
@bantu FYI – this library is used by ownCloud as well, the test suite is failing on HHVM with:

```
There was 1 failure:
1) CalendarTest::testFormat
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-GMT-1:02
+Fiji Standard Time
```

Thought not sure how relevant a test case containing Fiji Standard Time for us is…

**Comment by mlocati** [comment]
> Thought not sure how relevant a test case containing Fiji Standard Time for us is…

The problem is neither specific to the Fiji Standard Time not Punic related. It's more serious.
The problem is that hhvm does not correctly handle unnamed time zones (see http://3v4l.org/NqHVh )
It's a known hhvm issue (see https://github.com/facebook/hhvm/issues/3559 and https://github.com/facebook/hhvm/issues/1777 )

**Comment by Remo** [comment]
@mlocati can we use a workaround like this  https://github.com/agavi/agavi/commit/1d818acfd049f0c814b6be2599c76937d25e2510?

**Comment by mlocati** [comment]
Maybe... https://github.com/punic/punic/pull/64

**Comment by mlocati** [comment]
Fixed!
