### ISSUE TITLE
How to handle locales named 'sr@latin'?

### ISSUE THREAD

**Issue by DeepDiver1975** [punic/punic#55]
see https://github.com/owncloud/core/issues/16207

Should we simply cut off the post fix '@latin'?

THX a lot!

**Comment by mlocati** [comment]
I'm not at the computer right now, but IIRC the accepted format as defined by CLDR (thus Punic) is `sr_Latn`

**Comment by mlocati** [comment]
IMHO it's important to keep the Latin script part because IIRC `sr` could default do Cyrillic...

**Comment by DeepDiver1975** [comment]
Thx a lot for your fast feedback - any idea on how we get from sr@latin to sr_latn ? Many thanks

**Comment by mlocati** [comment]
CLDR locale specs says that a locale is defined by `<language code>[_<script code>][_<territory code>]`.

- The language code is 2 or 3 letters (a-z).
- The script code is 4 letters(see https://github.com/unicode-cldr/cldr-localenames-full/blob/master/main/en/scripts.json)
- The territory code is 2 letters (a-z) or 3 digits

I don't know whigh is the origin of your `sr@latin`, but IMHO a simple re get and  a table lookup to encode the script could be enough. Furthermore this shouldn't impact performance because you can set the default locale for Punic: if you do that when you initialize the current locale (or change the current locale), you don't have to do it every time you call punic functions... Sorry if I'm not really clear: 5" screens and tiny virtual keyboards have their limits :wink:

**Comment by DeepDiver1975** [comment]
Thanks a lot! We will go with a lookup then - THX
