### ISSUE TITLE
Korean localePattern missing a space

### ISSUE THREAD

**Issue by Seanom** [punic/punic#63]
I've just run into an issue with the localePattern for Korean. On closer inspection I notice this is not consistent with other languages, 'punic/code/data/ko/localeDisplayNames.json'

    localePattern":"%1$s(%2$s)

All other languages use 

    localePattern":"%1$s (%2$s)

**Comment by mlocati** [comment]
The json data comes from CLDR, so you should fix errors there.
Fixing CLDR errors is quite easy:
- read the page http://cldr.unicode.org/index/survey-tool/accounts
- go to http://www.unicode.org/reporting.html
- fill-in all the fields, and in particular in the field "Type of Message" choose "Request for CLDR Submitter ID"

You'll then receive a CLDR account and you'll be able to contribute to the CLDR data, fixing errors like the one that you reported.

Please note that you can submit data to CLDR only in the periods specified here: http://cldr.unicode.org/index#TOC-General-Schedule- (and you're quite lucky: data submission it's currently open).

I'm going to close this issue since it's not a Punic issue, but a CLDR issue...
