### ISSUE TITLE
Supporting more languages

### ISSUE THREAD

**Issue by danmichaelo** [punic/punic#75]
Specifically I would like to see support for `nn`. It would also be nice if the readme could mention or link to a list of supported languages, and describe the process for adding more. Let me know if I can help with something.

**Comment by Remo** [comment]
We are using the CLDR data http://cldr.unicode.org/
If you want another language you'll have to check with them!

**Comment by mlocati** [comment]
CLDR already defines `nn`, but it's not included by default in Punic.

In order to have all the CLDR languages available in Punic, download a copy of this repo (with the `Download ZIP` button available at https://github.com/punic/punic ) or clone it (if you know what that means), open a console and enter this command:
`<Path/to/Punic>/bin/build.sh full` (for *nix/Mac)
or
`<Path\to\Punic>\bin\build.cmd full` (for Windows)

**Comment by mlocati** [comment]
PS: the list of locales available by default it listed here: https://github.com/punic/punic/blob/1.6.3/bin/build.php#L191

**Comment by danmichaelo** [comment]
Thanks @mlocati ! Is the reason for not including more languages directly in the distribution that you want to save disk space? Would you accept a pull request for adding `nn`?

**Comment by mlocati** [comment]
The reason to not include all the languages is the size, you're right: the size of the `data` folder with all the available CLDR locales is about 80 MB (instead of the current 5 MB).
Yes, I'd be glad to add `nn` :wink:

**Comment by danmichaelo** [comment]
Cool, thanks for merging both :flags:
